[custom]
; 解决DNS泄露，无分流群组
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,[]GEOSITE,private
ruleset=DIRECT,[]GEOIP,private,no-resolve
ruleset=🚀 节点选择,https://raw.githubusercontent.com/1lkei/resources/refs/heads/main/proxyrule/self_black.list
ruleset=DIRECT,https://raw.githubusercontent.com/1lkei/resources/refs/heads/main/proxyrule/self_white.list
ruleset=DIRECT,[]GEOSITE,apple
ruleset=DIRECT,[]GEOSITE,category-ai-cn
ruleset=DIRECT,[]GEOSITE,cn
ruleset=DIRECT,[]GEOIP,CN,no-resolve
ruleset=🤖 AI服务,[]GEOSITE,category-ai-!cn
ruleset=🌐 社交平台(x|telegram|tiktok|google),[]GEOIP,telegram,no-resolve
ruleset=🌐 社交平台(x|telegram|tiktok|google),[]GEOSITE,x
ruleset=🌐 社交平台(x|telegram|tiktok|google),[]GEOSITE,telegram
ruleset=🌐 社交平台(x|telegram|tiktok|google),[]GEOSITE,tiktok
ruleset=🌐 社交平台(x|telegram|tiktok|google),[]GEOSITE,google
ruleset=☁️ PikPak,[]GEOSITE,pikpak
ruleset=🎯 个别域名,[]GEOSITE,javdb
ruleset=🧭 默认策略,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🤖 AI服务`select`[]🚀 节点选择`[]REJECT`.*
custom_proxy_group=☁️ PikPak`select`[]🚀 节点选择`.*
custom_proxy_group=🌐 社交平台(x|telegram|tiktok|google)`select`[]🚀 节点选择`.*
custom_proxy_group=🎯 个别域名`select`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=🧭 默认策略`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`[]REJECT`.*

enable_rule_generator=true
overwrite_original_rules=true